#!/bin/sh

for USER_NAME in `users`
do
    #echo $USER_NAME
    USER_ID=`id -u $USER_NAME`
    #echo $USER_ID
    sudo -u $USER_NAME DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$USER_ID/bus /usr/bin/notify-send "S.M.A.R.T Error ($SMARTD_FAILTYPE)" "$SMARTD_MESSAGE" --icon=dialog-warning -u critical
done